/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Busca.*;
import Controller.Cadastro.*;
import View.Busca.*;
import View.Cadastro.*;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        Model.DAO.Persiste.getInstance();
        
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        MenuItemCliente = new javax.swing.JMenuItem();
        MenuItemFuncionario = new javax.swing.JMenuItem();
        MenuItemFornecedor = new javax.swing.JMenuItem();
        BarraFoda1 = new javax.swing.JPopupMenu.Separator();
        MenuItemCarteirinha = new javax.swing.JMenuItem();
        BarraFoda2 = new javax.swing.JPopupMenu.Separator();
        MenuItemBairro = new javax.swing.JMenuItem();
        MenuItemCidade = new javax.swing.JMenuItem();
        MenuItemEndereco = new javax.swing.JMenuItem();
        BarraFoda3 = new javax.swing.JPopupMenu.Separator();
        MenuItemProduto = new javax.swing.JMenuItem();
        BarraFoda4 = new javax.swing.JPopupMenu.Separator();
        MenuItemSair = new javax.swing.JMenuItem();
        jMenuMovimentos = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        Pagar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SisCan - Sistemas de Cantinas");

        jMenuBar.setPreferredSize(new java.awt.Dimension(252, 28));

        jMenuCadastros.setText("Cadastros");

        MenuItemCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        MenuItemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens_rob/People.png"))); // NOI18N
        MenuItemCliente.setText("Cliente");
        MenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemClienteActionPerformed(evt);
            }
        });
        jMenuCadastros.add(MenuItemCliente);

        MenuItemFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        MenuItemFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens_rob/Boss.png"))); // NOI18N
        MenuItemFuncionario.setText("Funcionário");
        MenuItemFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemFuncionarioActionPerformed(evt);
            }
        });
        jMenuCadastros.add(MenuItemFuncionario);

        MenuItemFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        MenuItemFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens_rob/Male.png"))); // NOI18N
        MenuItemFornecedor.setText("Fornecedor");
        MenuItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemFornecedorActionPerformed(evt);
            }
        });
        jMenuCadastros.add(MenuItemFornecedor);
        jMenuCadastros.add(BarraFoda1);

        MenuItemCarteirinha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        MenuItemCarteirinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens_rob/Message.png"))); // NOI18N
        MenuItemCarteirinha.setText("Carteirinha");
        MenuItemCarteirinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCarteirinhaActionPerformed(evt);
            }
        });
        jMenuCadastros.add(MenuItemCarteirinha);
        jMenuCadastros.add(BarraFoda2);

        MenuItemBairro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        MenuItemBairro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens_rob/Home.png"))); // NOI18N
        MenuItemBairro.setText("Bairro");
        MenuItemBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemBairroActionPerformed(evt);
            }
        });
        jMenuCadastros.add(MenuItemBairro);

        MenuItemCidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        MenuItemCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens_rob/Home.png"))); // NOI18N
        MenuItemCidade.setText("Cidade");
        MenuItemCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCidadeActionPerformed(evt);
            }
        });
        jMenuCadastros.add(MenuItemCidade);

        MenuItemEndereco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        MenuItemEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens_rob/Home.png"))); // NOI18N
        MenuItemEndereco.setText("Endereço");
        MenuItemEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEnderecoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(MenuItemEndereco);
        jMenuCadastros.add(BarraFoda3);

        MenuItemProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        MenuItemProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens_rob/Buy.png"))); // NOI18N
        MenuItemProduto.setText("Produto");
        MenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemProdutoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(MenuItemProduto);
        jMenuCadastros.add(BarraFoda4);

        MenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        MenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens_rob/Exit.png"))); // NOI18N
        MenuItemSair.setText("Sair");
        MenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSairActionPerformed(evt);
            }
        });
        jMenuCadastros.add(MenuItemSair);

        jMenuBar.add(jMenuCadastros);

        jMenuMovimentos.setText("Movimentos");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens_rob/Clipboard.png"))); // NOI18N
        jMenu1.setText("Contas");

        Pagar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        Pagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens_rob/Bookmark.png"))); // NOI18N
        Pagar.setText("Pagar");
        jMenu1.add(Pagar);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens_rob/Green bookmark.png"))); // NOI18N
        jMenuItem2.setText("Receber");
        jMenu1.add(jMenuItem2);

        jMenuMovimentos.add(jMenu1);

        jMenuBar.add(jMenuMovimentos);

        jMenuRelatorios.setText("Relatórios");
        jMenuBar.add(jMenuRelatorios);

        jMenuAjuda.setText("Ajuda");
        jMenuBar.add(jMenuAjuda);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemBairroActionPerformed
        CadastroBairro cadastroBairro = new CadastroBairro();
        ControllerCadastroBairro controllerCadastroBairro = new ControllerCadastroBairro(cadastroBairro);
        cadastroBairro.setVisible(true);
    }//GEN-LAST:event_MenuItemBairroActionPerformed

    private void MenuItemCarteirinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCarteirinhaActionPerformed
        CadastroCarteirinha cadastroCarteirinha = new CadastroCarteirinha();
        ControllerCadastroCarteirinha controllerCadastroCarteirinha = new ControllerCadastroCarteirinha(cadastroCarteirinha);
        cadastroCarteirinha.setVisible(true);
    }//GEN-LAST:event_MenuItemCarteirinhaActionPerformed

    private void MenuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemFornecedorActionPerformed
        CadastroFornecedor cadastroFornecedor = new CadastroFornecedor();
        ControllerCadastroFornecedor controllerCadastroFornecedor = new ControllerCadastroFornecedor(cadastroFornecedor);
        cadastroFornecedor.setVisible(true);
    }//GEN-LAST:event_MenuItemFornecedorActionPerformed

    private void MenuItemCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCidadeActionPerformed
        CadastroCidade cadastroCidade = new CadastroCidade();
        ControllerCadastroCidade controllerCadastroCidade = new ControllerCadastroCidade(cadastroCidade);
        cadastroCidade.setVisible(true);
    }//GEN-LAST:event_MenuItemCidadeActionPerformed

    private void MenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSairActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_MenuItemSairActionPerformed

    private void MenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemClienteActionPerformed
        CadastroCliente cadastroCliente = new CadastroCliente();
        ControllerCadastroCliente controllerCadastroCliente = new ControllerCadastroCliente(cadastroCliente);
        cadastroCliente.setVisible(true);
    }//GEN-LAST:event_MenuItemClienteActionPerformed

    private void MenuItemFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemFuncionarioActionPerformed
        CadastroFuncionario cadastroFuncionario = new CadastroFuncionario();
        ControllerCadastroFuncionario controllerCadastroFuncionario = new ControllerCadastroFuncionario(cadastroFuncionario);
        cadastroFuncionario.setVisible(true);
    }//GEN-LAST:event_MenuItemFuncionarioActionPerformed

    private void MenuItemEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEnderecoActionPerformed
        CadastroEndereco cadastroEndereco = new CadastroEndereco();
        ControllerCadastroEndereco controllerCadastroEndereco = new ControllerCadastroEndereco(cadastroEndereco);
        cadastroEndereco.setVisible(true);
    }//GEN-LAST:event_MenuItemEnderecoActionPerformed

    private void MenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemProdutoActionPerformed
        CadastroProduto cadastroProduto = new CadastroProduto();
        ControllerCadastroProduto controllerCadastroProduto = new ControllerCadastroProduto(cadastroProduto);
        cadastroProduto.setVisible(true);
    }//GEN-LAST:event_MenuItemProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator BarraFoda1;
    private javax.swing.JPopupMenu.Separator BarraFoda2;
    private javax.swing.JPopupMenu.Separator BarraFoda3;
    private javax.swing.JPopupMenu.Separator BarraFoda4;
    private javax.swing.JMenuItem MenuItemBairro;
    private javax.swing.JMenuItem MenuItemCarteirinha;
    private javax.swing.JMenuItem MenuItemCidade;
    private javax.swing.JMenuItem MenuItemCliente;
    private javax.swing.JMenuItem MenuItemEndereco;
    private javax.swing.JMenuItem MenuItemFornecedor;
    private javax.swing.JMenuItem MenuItemFuncionario;
    private javax.swing.JMenuItem MenuItemProduto;
    private javax.swing.JMenuItem MenuItemSair;
    private javax.swing.JMenuItem Pagar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMenuMovimentos;
    private javax.swing.JMenu jMenuRelatorios;
    // End of variables declaration//GEN-END:variables

   
}
